import { t } from '@lingui/macro'

import { EncumbranceUnit } from '@/domain/encumbrance'
import type { EquipmentItem } from '@/domain/equipment'

export const MiscEquipmentItems = (): ReadonlyArray<EquipmentItem> => [
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    details: t`config.misc.airBladder.details`,
    name: t`Air Bladder`,
    points: EncumbranceUnit.None,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 20,
    name: t`Bedroll`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 20,
    name: t`Block and Tackle`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 30,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    name: t`Book, Blank`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Book, Reading`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 200,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1000,
    name: t`Book, Spell (Blank)`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 5,
    details: t`config.misc.caltrop.details`,
    name: t`Caltrop`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    details: t`Emits light in a 10' radius. Burns for 2 hours.`,
    name: t`Candle`,
    points: EncumbranceUnit.None,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Chain, per foot`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 20,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    details: t`Chalk is useful for “blazing a trail” through a dungeon or
ruin, to ensure that the adventurers can find their way
back out again`,
    name: t`Chalk`,
    points: EncumbranceUnit.None,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    details: t`Charcoal pieces of carbonized wood, which can be used like chalk (with black markings), or to add to tinder`,
    name: t`Charcoal`,
    points: EncumbranceUnit.None,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 200,
    details: t`Provided price is minimal`,
    name: t`Clothing, Extravagant`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    name: t`Clothing, Normal`,
    points: EncumbranceUnit.None,
    ruralCostCp: 20,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Clothing, Poor`,
    points: EncumbranceUnit.None,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Clothing, Winter Travel`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Cooking Pots`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    details: t`Spikes for your boots – better success at climbing and keeping balance on ice`,
    name: t`Crampons`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 20,
    name: t`Crowbar`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 20,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    name: t`Drill`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Fishing Gear`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 5,
    name: t`Flask of Lamp Oil`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 3,
    name: t`Garlic`,
    points: EncumbranceUnit.None,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    details: t`Provided price is minimal`,
    name: t`Gem`,
    points: EncumbranceUnit.None,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    name: t`Grappling Hook`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 250,
    name: t`Holy Symbol, Silver`,
    points: EncumbranceUnit.None,
    ruralCostCp: 500,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Holy Symbol, Steel`,
    points: EncumbranceUnit.None,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Holy Symbol, Wood`,
    points: EncumbranceUnit.None,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 250,
    name: t`Holy Water`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 250,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1000,
    name: t`Hourglass`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    details: t`Writing ink: Stored in a small ceramic jar or tin and sufficient for 50 pages of normal writing`,
    name: t`Ink`,
    points: EncumbranceUnit.None,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    details: t`Provided price is minimal`,
    name: t`Instrument`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    details: t`Provided price is minimal`,
    name: t`Jewelry`,
    points: EncumbranceUnit.None,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Ladder, 10'`,
    points: EncumbranceUnit.Oversized,
    ruralCostCp: 70,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 30,
    details: t`Emits light in a 30' radius. Burns for 4 hours. Uses flasks of oil as fuel.`,
    name: t`Lantern`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    name: t`Lard`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 70,
    name: t`Lock`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 3,
    details: t`A hammer or mallet with a head made of
treated wood, plant resins, or other materials. The head of
this hammer makes very little sound when striking things
(such as a stake, nail, or head). This does not keep what
is being hit from making noise – a glass window will still
make noise when it shatters.`,
    name: t`Mallet`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 3,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Manacles`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 150,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Map, Kingdom`,
    points: EncumbranceUnit.None,
    ruralCostCp: 250,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Map, Local`,
    points: EncumbranceUnit.None,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    details: t`Mirrors are useful for many reasons; for instance, they can be used for looking around corners or for sending signals outdoors using reflected sunlight.`,
    name: t`Mirror, Glass`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 150,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 300,
    details: t`Mirrors are useful for many reasons; for instance, they can be used for looking around corners or for sending signals outdoors using reflected sunlight.`,
    name: t`Mirror, Silver`,
    points: EncumbranceUnit.None,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    details: t`Mirrors are useful for many reasons; for instance, they can be used for looking around corners or for sending signals outdoors using reflected sunlight.`,
    name: t`Mirror, Steel`,
    points: EncumbranceUnit.None,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    name: t`Nails`,
    points: EncumbranceUnit.None,
    ruralCostCp: 2,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 2,
    name: t`Paper`,
    points: EncumbranceUnit.None,
    ruralCostCp: 2,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 60,
    name: t`Pick, Miner’s`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 120,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Pipe`,
    points: EncumbranceUnit.None,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Pole, 10'`,
    points: EncumbranceUnit.Oversized,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 250,
    name: t`Riding Gear`,
    points: EncumbranceUnit.Oversized,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 30,
    name: t`Rope, 50'`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 30,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Scroll Case`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 30,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 30,
    name: t`Shovel`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 30,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    name: t`Soap`,
    points: EncumbranceUnit.None,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 500,
    name: t`Specialist’s Tools`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 3,
    details: t`Spikes are useful for spiking doors closed (or spiking them open) and may be used as crude pitons in appropriate situations.`,
    name: t`Spike, Iron`,
    points: EncumbranceUnit.None,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    details: t`Spikes are useful for spiking doors closed (or spiking them open) and may be used as crude pitons in appropriate situations.`,
    name: t`Spike, Wooden`,
    points: EncumbranceUnit.None,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 2500,
    name: t`Spyglass`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 250,
    name: t`Tent, Grand`,
    points: EncumbranceUnit.Oversized,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 500,
    name: t`Tent, Pavilion`,
    points: EncumbranceUnit.Oversized,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    name: t`Tent, Personal`,
    points: EncumbranceUnit.Oversized,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Tent, Regular`,
    points: EncumbranceUnit.Oversized,
    ruralCostCp: 200,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    details: t`A Tinderbox is generally purchased with a flint and steel;
the flint, a piece of hard rock, is struck vigorously against a C-shaped piece of high-carbon steel. 
When done correctly, hot sparks will fly from the flint and steel into the tinder, hopefully starting a fire.`,
    name: t`Tinderbox`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Tobacco`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    details: t`Emits light in a 30' radius. Burns for 1 hour.`,
    name: t`Torch`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 5,
    details: t`No encumbrance if empty`,
    name: t`Vial or Bottle`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 7,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    details: t`Wineskin/Waterskin is a container for drinking water or
wine; though generally water is taken into a dungeon or
wilderness environment. The standard waterskin holds
one quart of liquid, which is the minimum amount
required by a normal character in a single day.`,
    name: t`Waterskin`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Whistle`,
    points: EncumbranceUnit.None,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Wolvesbane`,
    points: EncumbranceUnit.None,
    ruralCostCp: 1,
  },
  // FOOD + DRINKS
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 20,
    details: t`Iron (dry) Rations may consist of dry bread, hard cheese, dried
fruit, nuts, beans, jerky, or any other food which will not
“go bad” in less than about a month (if not longer). Dry
rations are packaged in waxed or oiled cloth to protect them`,
    name: t`Rations, Iron/Day`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    details: t`Standard Rations include cured meats, seasonal fruits
and vegetables, and fresh breads or biscuits, often
wrapped in cloth. These are tastier than dry rations, but
will generally only keep for a few days in all but the coldest
or driest climates (up to 1 week)`,
    name: t`Rations, Standard/Day`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Feed, Animal/Day`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 5,
    name: t`Bottle of Wine/Liquor, Poor`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 2,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    details: t`Provided price is minimal`,
    name: t`Bottle of Wine/Liquor, Decent`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    details: t`Provided price is minimal`,
    name: t`Bottle of Wine/Liquor, Rich`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: null,
  },
  // CONTAINERS
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 30,
    name: t`Backpack`,
    points: EncumbranceUnit.None,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Barrel`,
    points: EncumbranceUnit.Oversized,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Chest`,
    points: EncumbranceUnit.Oversized,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 5,
    name: t`Pouch`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    name: t`Quiver`,
    points: EncumbranceUnit.Regular,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 5,
    name: t`Sack`,
    points: EncumbranceUnit.None,
    ruralCostCp: 2,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Saddlebag`,
    points: EncumbranceUnit.None,
    ruralCostCp: 5,
  },
]
