import { msg } from '@lingui/macro'

import type { EquipmentItemTranslated } from '@/config/types'
import type { EquipmentItem } from '@/domain'
import { EncumbrancePoint } from '@/domain/encumbrance'

export const MiscEquipment: ReadonlyArray<
  EquipmentItemTranslated<EquipmentItem>
> = [
  {
    cityCost: 1,
    details: msg`config.misc.airBladder.details`,
    name: msg`Air Bladder`,
    points: EncumbrancePoint.None,
    ruralCost: 1,
  },
  {
    cityCost: 2,
    name: msg`Bedroll`,
    points: EncumbrancePoint.Regular,
    ruralCost: 1,
  },
  {
    cityCost: 2,
    name: msg`Block and Tackle`,
    points: EncumbrancePoint.Regular,
    ruralCost: 3,
  },
  {
    cityCost: 5,
    name: msg`Book, Blank`,
    points: EncumbrancePoint.Regular,
    ruralCost: 10,
  },
  {
    cityCost: 10,
    name: msg`Book, Reading`,
    points: EncumbrancePoint.Regular,
    ruralCost: 20,
  },
  {
    cityCost: 100,
    name: msg`Book, Spell (Blank)`,
    points: EncumbrancePoint.Regular,
    ruralCost: null,
  },
  {
    cityCost: 0.5,
    details: msg`config.misc.caltrop.details`,
    name: msg`Caltrop`,
    points: EncumbrancePoint.Regular,
    ruralCost: null,
  },
  {
    cityCost: 0.1,
    name: msg`Candle`,
    points: EncumbrancePoint.None,
    ruralCost: 0.1,
  },
  {
    cityCost: 1,
    name: msg`Chain, per foot`,
    points: EncumbrancePoint.Regular,
    ruralCost: 2,
  },
  {
    cityCost: 0.1,
    name: msg`Chalk`,
    points: EncumbrancePoint.None,
    ruralCost: 0.1,
  },
  {
    cityCost: 20,
    details: msg`Provided price is minimal`,
    name: msg`Clothing, Extravagant`,
    points: EncumbrancePoint.Regular,
    ruralCost: null,
  },
  {
    cityCost: 5,
    name: msg`Clothing, Normal`,
    points: EncumbrancePoint.None,
    ruralCost: 2,
  },
  {
    cityCost: 1,
    name: msg`Clothing, Poor`,
    points: EncumbrancePoint.None,
    ruralCost: 0.5,
  },
  {
    cityCost: 10,
    name: msg`Clothing, Winter Travel`,
    points: EncumbrancePoint.Regular,
    ruralCost: 5,
  },
  {
    cityCost: 1,
    name: msg`Cooking Pots`,
    points: EncumbrancePoint.Regular,
    ruralCost: 0.5,
  },
  {
    cityCost: 5,
    name: msg`Crampons`,
    points: EncumbrancePoint.Regular,
    ruralCost: 5,
  },
  {
    cityCost: 2,
    name: msg`Crowbar`,
    points: EncumbrancePoint.Regular,
    ruralCost: 2,
  },
  {
    cityCost: 5,
    name: msg`Drill`,
    points: EncumbrancePoint.Regular,
    ruralCost: 5,
  },
  {
    cityCost: 1,
    name: msg`Fishing Gear`,
    points: EncumbrancePoint.Regular,
    ruralCost: 1,
  },
  {
    cityCost: 0.5,
    name: msg`Flask of Lamp Oil`,
    points: EncumbrancePoint.Regular,
    ruralCost: 0.5,
  },
  {
    cityCost: 0.3,
    name: msg`Garlic`,
    points: EncumbrancePoint.None,
    ruralCost: 0.1,
  },
  {
    cityCost: 5,
    details: msg`Provided price is minimal`,
    name: msg`Gem`,
    points: EncumbrancePoint.None,
    ruralCost: 5,
  },
  {
    cityCost: 5,
    name: msg`Grappling Hook`,
    points: EncumbrancePoint.Regular,
    ruralCost: 10,
  },
  {
    cityCost: 25,
    name: msg`Holy Symbol, Silver`,
    points: EncumbrancePoint.None,
    ruralCost: 50,
  },
  {
    cityCost: 10,
    name: msg`Holy Symbol, Steel`,
    points: EncumbrancePoint.None,
    ruralCost: 10,
  },
  {
    cityCost: 1,
    name: msg`Holy Symbol, Wood`,
    points: EncumbrancePoint.None,
    ruralCost: 0.1,
  },
  {
    cityCost: 25,
    name: msg`Holy Water`,
    points: EncumbrancePoint.Regular,
    ruralCost: 25,
  },
  {
    cityCost: 100,
    name: msg`Hourglass`,
    points: EncumbrancePoint.Regular,
    ruralCost: null,
  },
  {
    cityCost: 0.1,
    name: msg`Ink`,
    points: EncumbrancePoint.None,
    ruralCost: 0.5,
  },
  {
    cityCost: 1,
    details: msg`Provided price is minimal`,
    name: msg`Instrument`,
    points: EncumbrancePoint.Regular,
    ruralCost: 5,
  },
  {
    cityCost: 10,
    details: msg`Provided price is minimal`,
    name: msg`Jewelry`,
    points: EncumbrancePoint.None,
    ruralCost: 10,
  },
  {
    cityCost: 10,
    name: msg`Ladder, 10'`,
    points: EncumbrancePoint.Oversized,
    ruralCost: 7,
  },
  {
    cityCost: 3,
    name: msg`Lantern`,
    points: EncumbrancePoint.Regular,
    ruralCost: 5,
  },
  {
    cityCost: 0.1,
    name: msg`Lard`,
    points: EncumbrancePoint.Regular,
    ruralCost: 0.1,
  },
  {
    cityCost: 7,
    name: msg`Lock`,
    points: EncumbrancePoint.Regular,
    ruralCost: 10,
  },
  {
    cityCost: 0.3,
    name: msg`Mallet`,
    points: EncumbrancePoint.Regular,
    ruralCost: 0.3,
  },
  {
    cityCost: 10,
    name: msg`Manacles`,
    points: EncumbrancePoint.Regular,
    ruralCost: 15,
  },
  {
    cityCost: 10,
    name: msg`Map, Kingdom`,
    points: EncumbrancePoint.None,
    ruralCost: 25,
  },
  {
    cityCost: 1,
    name: msg`Map, Local`,
    points: EncumbrancePoint.None,
    ruralCost: 5,
  },
  {
    cityCost: 10,
    name: msg`Mirror, Glass`,
    points: EncumbrancePoint.Regular,
    ruralCost: 15,
  },
  {
    cityCost: 30,
    name: msg`Mirror, Silver`,
    points: EncumbrancePoint.None,
    ruralCost: null,
  },
  {
    cityCost: 1,
    name: msg`Mirror, Steel`,
    points: EncumbrancePoint.None,
    ruralCost: 5,
  },
  {
    cityCost: 0.1,
    name: msg`Nails`,
    points: EncumbrancePoint.None,
    ruralCost: 0.2,
  },
  {
    cityCost: 0.2,
    name: msg`Paper`,
    points: EncumbrancePoint.None,
    ruralCost: 0.2,
  },
  {
    cityCost: 6,
    name: msg`Pick, Miner’s`,
    points: EncumbrancePoint.Regular,
    ruralCost: 12,
  },
  {
    cityCost: 1,
    name: msg`Pipe`,
    points: EncumbrancePoint.None,
    ruralCost: 0.5,
  },
  {
    cityCost: 1,
    name: msg`Pole, 10'`,
    points: EncumbrancePoint.Oversized,
    ruralCost: 0.5,
  },
  {
    cityCost: 25,
    name: msg`Riding Gear`,
    points: EncumbrancePoint.Oversized,
    ruralCost: 10,
  },
  {
    cityCost: 3,
    name: msg`Rope, 50'`,
    points: EncumbrancePoint.Regular,
    ruralCost: 3,
  },
  {
    cityCost: 1,
    name: msg`Scroll Case`,
    points: EncumbrancePoint.Regular,
    ruralCost: 3,
  },
  {
    cityCost: 3,
    name: msg`Shovel`,
    points: EncumbrancePoint.Regular,
    ruralCost: 3,
  },
  {
    cityCost: 0.1,
    name: msg`Soap`,
    points: EncumbrancePoint.None,
    ruralCost: 0.1,
  },
  {
    cityCost: 50,
    name: msg`Specialist’s Tools`,
    points: EncumbrancePoint.Regular,
    ruralCost: null,
  },
  {
    cityCost: 0.3,
    name: msg`Spike, Iron`,
    points: EncumbrancePoint.None,
    ruralCost: 0.5,
  },
  {
    cityCost: 0.1,
    name: msg`Spike, Wooden`,
    points: EncumbrancePoint.None,
    ruralCost: 0.1,
  },
  {
    cityCost: 250,
    name: msg`Spyglass`,
    points: EncumbrancePoint.Regular,
    ruralCost: null,
  },
  {
    cityCost: 25,
    name: msg`Tent, Grand`,
    points: EncumbrancePoint.Oversized,
    ruralCost: null,
  },
  {
    cityCost: 50,
    name: msg`Tent, Pavilion`,
    points: EncumbrancePoint.Oversized,
    ruralCost: null,
  },
  {
    cityCost: 5,
    name: msg`Tent, Personal`,
    points: EncumbrancePoint.Oversized,
    ruralCost: 10,
  },
  {
    cityCost: 10,
    name: msg`Tent, Regular`,
    points: EncumbrancePoint.Oversized,
    ruralCost: 20,
  },
  {
    cityCost: 1,
    name: msg`Tinderbox`,
    points: EncumbrancePoint.Regular,
    ruralCost: 5,
  },
  {
    cityCost: 1,
    name: msg`Tobacco`,
    points: EncumbrancePoint.Regular,
    ruralCost: 0.5,
  },
  {
    cityCost: 0.1,
    name: msg`Torch`,
    points: EncumbrancePoint.Regular,
    ruralCost: 0.1,
  },
  {
    cityCost: 0.5,
    details: msg`No encumbrance if empty`,
    name: msg`Vial or Bottle`,
    points: EncumbrancePoint.Regular,
    ruralCost: 0.7,
  },
  {
    cityCost: 1,
    name: msg`Waterskin`,
    points: EncumbrancePoint.Regular,
    ruralCost: 1,
  },
  {
    cityCost: 1,
    name: msg`Whistle`,
    points: EncumbrancePoint.None,
    ruralCost: 1,
  },
  {
    cityCost: 1,
    name: msg`Wolvesbane`,
    points: EncumbrancePoint.None,
    ruralCost: 0.1,
  },
  // FOOD + DRINKS
  {
    cityCost: 2,
    name: msg`Rations, Iron/Day`,
    points: EncumbrancePoint.Regular,
    ruralCost: 1,
  },
  {
    cityCost: 1,
    name: msg`Rations, Standard/Day`,
    points: EncumbrancePoint.Regular,
    ruralCost: 0.5,
  },
  {
    cityCost: 1,
    name: msg`Feed, Animal/Day`,
    points: EncumbrancePoint.Regular,
    ruralCost: 0.5,
  },
  {
    cityCost: 0.5,
    name: msg`Bottle of Wine/Liquor, Poor`,
    points: EncumbrancePoint.Regular,
    ruralCost: 0.2,
  },
  {
    cityCost: 1,
    details: msg`Provided price is minimal`,
    name: msg`Bottle of Wine/Liquor, Decent`,
    points: EncumbrancePoint.Regular,
    ruralCost: 1,
  },
  {
    cityCost: 10,
    details: msg`Provided price is minimal`,
    name: msg`Bottle of Wine/Liquor, Rich`,
    points: EncumbrancePoint.Regular,
    ruralCost: null,
  },
  // CONTAINERS
  {
    cityCost: 3,
    name: msg`Backpack`,
    points: EncumbrancePoint.None,
    ruralCost: 1,
  },
  {
    cityCost: 1,
    name: msg`Barrel`,
    points: EncumbrancePoint.Oversized,
    ruralCost: 5,
  },
  {
    cityCost: 10,
    name: msg`Chest`,
    points: EncumbrancePoint.Oversized,
    ruralCost: 5,
  },
  {
    cityCost: 0.5,
    name: msg`Pouch`,
    points: EncumbrancePoint.Regular,
    ruralCost: 0.1,
  },
  {
    cityCost: 5,
    name: msg`Quiver`,
    points: EncumbrancePoint.Regular,
    ruralCost: 10,
  },
  {
    cityCost: 0.5,
    name: msg`Sack`,
    points: EncumbrancePoint.None,
    ruralCost: 0.2,
  },
  {
    cityCost: 1,
    name: msg`Saddlebag`,
    points: EncumbrancePoint.None,
    ruralCost: 0.5,
  },
]
