import { t } from '@lingui/macro'

import { EncumbrancePoint } from '@/domain/encumbrance'
import type { EquipmentItem } from '@/domain/equipment'

export const MiscEquipmentItems = (): ReadonlyArray<EquipmentItem> => [
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    details: t`config.misc.airBladder.details`,
    name: t`Air Bladder`,
    points: EncumbrancePoint.None,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 20,
    name: t`Bedroll`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 20,
    name: t`Block and Tackle`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 30,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    name: t`Book, Blank`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Book, Reading`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 200,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1000,
    name: t`Book, Spell (Blank)`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 5,
    details: t`config.misc.caltrop.details`,
    name: t`Caltrop`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    name: t`Candle`,
    points: EncumbrancePoint.None,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Chain, per foot`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 20,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    name: t`Chalk`,
    points: EncumbrancePoint.None,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 200,
    details: t`Provided price is minimal`,
    name: t`Clothing, Extravagant`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    name: t`Clothing, Normal`,
    points: EncumbrancePoint.None,
    ruralCostCp: 20,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Clothing, Poor`,
    points: EncumbrancePoint.None,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Clothing, Winter Travel`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Cooking Pots`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    name: t`Crampons`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 20,
    name: t`Crowbar`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 20,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    name: t`Drill`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Fishing Gear`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 5,
    name: t`Flask of Lamp Oil`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 3,
    name: t`Garlic`,
    points: EncumbrancePoint.None,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    details: t`Provided price is minimal`,
    name: t`Gem`,
    points: EncumbrancePoint.None,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    name: t`Grappling Hook`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 250,
    name: t`Holy Symbol, Silver`,
    points: EncumbrancePoint.None,
    ruralCostCp: 500,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Holy Symbol, Steel`,
    points: EncumbrancePoint.None,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Holy Symbol, Wood`,
    points: EncumbrancePoint.None,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 250,
    name: t`Holy Water`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 250,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1000,
    name: t`Hourglass`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    name: t`Ink`,
    points: EncumbrancePoint.None,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    details: t`Provided price is minimal`,
    name: t`Instrument`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    details: t`Provided price is minimal`,
    name: t`Jewelry`,
    points: EncumbrancePoint.None,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Ladder, 10'`,
    points: EncumbrancePoint.Oversized,
    ruralCostCp: 70,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 30,
    name: t`Lantern`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    name: t`Lard`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 70,
    name: t`Lock`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 3,
    name: t`Mallet`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 3,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Manacles`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 150,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Map, Kingdom`,
    points: EncumbrancePoint.None,
    ruralCostCp: 250,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Map, Local`,
    points: EncumbrancePoint.None,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Mirror, Glass`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 150,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 300,
    name: t`Mirror, Silver`,
    points: EncumbrancePoint.None,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Mirror, Steel`,
    points: EncumbrancePoint.None,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    name: t`Nails`,
    points: EncumbrancePoint.None,
    ruralCostCp: 2,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 2,
    name: t`Paper`,
    points: EncumbrancePoint.None,
    ruralCostCp: 2,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 60,
    name: t`Pick, Miner’s`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 120,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Pipe`,
    points: EncumbrancePoint.None,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Pole, 10'`,
    points: EncumbrancePoint.Oversized,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 250,
    name: t`Riding Gear`,
    points: EncumbrancePoint.Oversized,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 30,
    name: t`Rope, 50'`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 30,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Scroll Case`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 30,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 30,
    name: t`Shovel`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 30,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    name: t`Soap`,
    points: EncumbrancePoint.None,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 500,
    name: t`Specialist’s Tools`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 3,
    name: t`Spike, Iron`,
    points: EncumbrancePoint.None,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    name: t`Spike, Wooden`,
    points: EncumbrancePoint.None,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 2500,
    name: t`Spyglass`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 250,
    name: t`Tent, Grand`,
    points: EncumbrancePoint.Oversized,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 500,
    name: t`Tent, Pavilion`,
    points: EncumbrancePoint.Oversized,
    ruralCostCp: null,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    name: t`Tent, Personal`,
    points: EncumbrancePoint.Oversized,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Tent, Regular`,
    points: EncumbrancePoint.Oversized,
    ruralCostCp: 200,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Tinderbox`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Tobacco`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 1,
    name: t`Torch`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 5,
    details: t`No encumbrance if empty`,
    name: t`Vial or Bottle`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 7,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Waterskin`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Whistle`,
    points: EncumbrancePoint.None,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Wolvesbane`,
    points: EncumbrancePoint.None,
    ruralCostCp: 1,
  },
  // FOOD + DRINKS
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 20,
    name: t`Rations, Iron/Day`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Rations, Standard/Day`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Feed, Animal/Day`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 5,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 5,
    name: t`Bottle of Wine/Liquor, Poor`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 2,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    details: t`Provided price is minimal`,
    name: t`Bottle of Wine/Liquor, Decent`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    details: t`Provided price is minimal`,
    name: t`Bottle of Wine/Liquor, Rich`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: null,
  },
  // CONTAINERS
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 30,
    name: t`Backpack`,
    points: EncumbrancePoint.None,
    ruralCostCp: 10,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Barrel`,
    points: EncumbrancePoint.Oversized,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 100,
    name: t`Chest`,
    points: EncumbrancePoint.Oversized,
    ruralCostCp: 50,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 5,
    name: t`Pouch`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 1,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 50,
    name: t`Quiver`,
    points: EncumbrancePoint.Regular,
    ruralCostCp: 100,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 5,
    name: t`Sack`,
    points: EncumbrancePoint.None,
    ruralCostCp: 2,
  },
  {
    categoryKey: 'miscEquipment',
    cityCostCp: 10,
    name: t`Saddlebag`,
    points: EncumbrancePoint.None,
    ruralCostCp: 5,
  },
]
