import { msg } from '@lingui/macro'

import type { EquipmentItemTranslated } from '@/config/types'
import { Dice } from '@/domain'
import { EncumbrancePoint } from '@/domain/encumbrance'
import type { MissileWeaponItem } from '@/domain/weapon'
import { WeaponType } from '@/domain/weapon'

export const MissileWeapons: ReadonlyArray<
  EquipmentItemTranslated<MissileWeaponItem>
> = [
  {
    cityCost: 5,
    damage: null,
    details: msg`config.missile.blowgun.details`,
    name: msg`Blowgun`,
    points: EncumbrancePoint.Regular,
    range: { long: 80, medium: 50, short: 20 },
    ruralCost: null,
    type: WeaponType.Missile,
  },
  {
    cityCost: 45,
    damage: { dice: Dice.d6, x: 1 },
    name: msg`Bow, Long`,
    points: EncumbrancePoint.Oversized,
    range: { long: 900, medium: 600, short: 50 },
    ruralCost: null,
    type: WeaponType.Missile,
  },
  {
    cityCost: 25,
    damage: { dice: Dice.d6, x: 1 },
    name: msg`Bow, Short`,
    points: EncumbrancePoint.Regular,
    range: { long: 450, medium: 300, short: 50 },
    ruralCost: 25,
    type: WeaponType.Missile,
  },
  {
    cityCost: 30,
    damage: { dice: Dice.d8, x: 1 },
    details: msg`Heavy crossbows can only be fired once in 3 rounds and ignore 4 AC points`,
    name: msg`Crossbow, Heavy`,
    points: EncumbrancePoint.Oversized,
    range: { long: 600, medium: 200, short: 50 },
    ruralCost: null,
    type: WeaponType.Missile,
  },
  {
    cityCost: 25,
    damage: { dice: Dice.d6, x: 1 },
    details: msg`Light crossbows can only be fired every once in 2 rounds and ignore 2 AC points`,
    name: msg`Crossbow, Light`,
    points: EncumbrancePoint.Regular,
    range: { long: 400, medium: 150, short: 50 },
    ruralCost: null,
    type: WeaponType.Missile,
  },
  {
    cityCost: 0,
    damage: { dice: Dice.d2, x: 1 },
    details: msg`A rock for throwing, not an ammunition`,
    name: msg`Rock`,
    points: EncumbrancePoint.None,
    range: { long: 30, medium: 20, short: 10 },
    ruralCost: 0,
    type: WeaponType.Missile,
  },
  {
    cityCost: 1,
    damage: { dice: Dice.d4, x: 1 },
    details: msg`Slings fired with stones instead of bullets have half the listed range.`,
    name: msg`Sling`,
    points: EncumbrancePoint.None,
    range: { long: 450, medium: 300, short: 50 },
    ruralCost: 0.5,
    type: WeaponType.Missile,
  },
  {
    cityCost: 1,
    damage: { dice: Dice.d4, x: 1 },
    name: msg`Dart`,
    points: EncumbrancePoint.Regular,
    range: { long: 30, medium: 20, short: 10 },
    ruralCost: null,
    type: WeaponType.Missile,
  },
  // AMMO
  {
    cityCost: 0.2,
    damage: null,
    details: msg`Slings fired with stones instead of bullets have half the listed range.`,
    name: msg`Sling bullets (10)`,
    points: EncumbrancePoint.Regular,
    range: { long: 450, medium: 300, short: 50 },
    ruralCost: 0.2,
    type: WeaponType.Ammunition,
  },
  {
    cityCost: 0,
    damage: null,
    details: msg`config.melee.slingRocks.details`,
    name: msg`Sling bullets, rocks (10)`,
    points: EncumbrancePoint.Regular,
    range: { long: 225, medium: 150, short: 25 },
    ruralCost: 0,
    type: WeaponType.Ammunition,
  },
  {
    cityCost: 0.5,
    damage: null,
    name: msg`Arrow (1)`,
    points: EncumbrancePoint.None,
    range: null,
    ruralCost: 0.5,
    type: WeaponType.Ammunition,
  },
  {
    cityCost: 10,
    damage: null,
    name: msg`Arrows, quiver (20)`,
    points: EncumbrancePoint.Regular,
    range: null,
    ruralCost: 10,
    type: WeaponType.Ammunition,
  },
  {
    cityCost: 0.5,
    damage: null,
    name: msg`Crossbow bolt (1)`,
    points: EncumbrancePoint.None,
    range: null,
    ruralCost: 0.5,
    type: WeaponType.Ammunition,
  },
  {
    cityCost: 10,
    damage: null,
    name: msg`Crossbow bolts, quiver (20)`,
    points: EncumbrancePoint.Regular,
    range: null,
    ruralCost: 10,
    type: WeaponType.Ammunition,
  },
  // Dart as an ammunition is taken from BFRPG Equipment Emporium 1e;
  {
    cityCost: 0.2,
    damage: { dice: Dice.d3, x: 1 },
    name: msg`Dart for blowgun (1)`,
    points: EncumbrancePoint.None,
    range: null,
    ruralCost: 0.2,
    type: WeaponType.Ammunition,
  },
  {
    cityCost: 4,
    damage: { dice: Dice.d3, x: 1 },
    name: msg`Darts for blowgun, quiver (20)`,
    points: EncumbrancePoint.Regular,
    range: null,
    ruralCost: 4,
    type: WeaponType.Ammunition,
  },
]
