import {Dice} from '@/shared/types'
import {EncumbrancePoint} from '@/shared/types/encumbrance'
import type {MeleeWeaponEntry} from '@/shared/types/weapon'

export const Weapons: MeleeWeaponEntry[] = [
  {
    id: 1,
    name: 'Cestus',
    cityCost: 10,
    ruralCost: null,
    points: EncumbrancePoint.None,
    damage: {
      x: 1,
      dice: Dice.d3,
    },
    isRecorded: false, // FIXME drop isRecorded at all?
  },
  {
    id: 2,
    name: 'Garrote',
    cityCost: 5,
    ruralCost: null,
    points: EncumbrancePoint.None,
    isRecorded: false,
    damage: {
      x: 1,
      dice: Dice.d6,
    },
  },
  {
    id: 3,
    name: 'Lance',
    cityCost: 30,
    ruralCost: null,
    points: EncumbrancePoint.Oversized,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d10,
    },
    isAbleToReceiveCharge: true,
    twoHanded: true,
    isSecondRank: true,
  },
  {
    id: 4,
    name: 'Mancatcher',
    cityCost: 20,
    ruralCost: null,
    points: EncumbrancePoint.Oversized,
    isRecorded: true,
    damage: null,
    isAbleToReceiveCharge: false,
    range: 5,
    twoHanded: true,
  },
  {
    id: 5,
    name: 'Polearm',
    cityCost: 30,
    ruralCost: null,
    points: EncumbrancePoint.Oversized,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d8,
    },
    twoHanded: true,
    isAbleToReceiveCharge: true,
    range: 10,
    isSecondRank: true,
  },
  {
    id: 6,
    name: 'Rapier',
    cityCost: 15,
    ruralCost: null,
    points: EncumbrancePoint.Regular,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d8,
    },
    range: 5,
  },
  {
    id: 7,
    name: 'Spear',
    cityCost: 5,
    ruralCost: 3,
    points: EncumbrancePoint.Regular,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d6,
    },
    range: 10,
    isAbleToReceiveCharge: true,
    twoHanded: false,
    isSecondRank: true,
  },
  {
    id: 8,
    name: 'Staff',
    cityCost: 5,
    ruralCost: 3,
    points: EncumbrancePoint.Regular,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d4,
    },
    range: 5,
  },
  {
    id: 9,
    name: 'Weapon, Great: Two-handed sword, maul, great axe',
    cityCost: 50,
    ruralCost: null,
    points: EncumbrancePoint.Oversized,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d10,
    },
    range: 5,
    twoHanded: true,
  },
  {
    id: 10,
    name: 'Weapon, Medium: sword, battle axe, mace',
    cityCost: 20,
    ruralCost: 50,
    points: EncumbrancePoint.Regular,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d8,
    },
    range: 5,
    twoHanded: false,
  },
  {
    id: 11,
    name: 'Weapon, Small: short sword, hand axe',
    cityCost: 10,
    ruralCost: 10,
    points: EncumbrancePoint.Regular,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d6,
    },
    range: 5,
  },
  {
    id: 12,
    name: 'Weapon, Minor: daggers, clubs',
    cityCost: 5,
    ruralCost: 5,
    points: EncumbrancePoint.Regular,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d4,
    },
    range: 5,
  },
  {
    id: 13,
    name: 'Whip',
    cityCost: 10,
    ruralCost: 25,
    points: EncumbrancePoint.Regular,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d3,
    },
    range: 10,
  },
]
