import {WeaponEntry} from "@/shared/types/weapon"
import {EncumbrancePoint} from "@/shared/types/encumbrance"
import {Dice} from "@/shared/types"

export const Weapons: WeaponEntry[] = [
  {
    id: 1,
    name: 'Cestus',
    cityCost: 10,
    ruralCost: null,
    points: EncumbrancePoint.None,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d3,
    },
    range: 0,
  },
  {
    id: 2,
    name: 'Garrote',
    cityCost: 5,
    ruralCost: null,
    points: EncumbrancePoint.None,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d6,
    },
    range: 0,
  },
  {
    id: 3,
    name: 'Lance',
    cityCost: 30,
    ruralCost: null,
    points: EncumbrancePoint.Oversized,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d10,
    },
    range: 10,
    isAbleToReceiveCharge: false,
    twoHanded: true,
    isSecondRank: true,
  },
  {
    id: 4,
    name: 'Mancatcher',
    cityCost: 20,
    ruralCost: null,
    points: EncumbrancePoint.Oversized,
    isRecorded: true,
    damage: null,
    isAbleToReceiveCharge: false,
    range: 5,
    twoHanded: true,
  },
  {
    id: 5,
    name: 'Polearm',
    cityCost: 30,
    ruralCost: null,
    points: EncumbrancePoint.Oversized,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d8,
    },
    twoHanded: true,
    isAbleToReceiveCharge: true,
    range: 10,
    isSecondRank: true,
  },
  {
    id: 6,
    name: 'Rapier',
    cityCost: 15,
    ruralCost: null,
    points: EncumbrancePoint.Regular,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d8,
    },
    range: 5,
  },
  {
    id: 7,
    name: 'Spear',
    cityCost: 5, 
    ruralCost: 3, 
    points: EncumbrancePoint.Regular, 
    isRecorded: true, 
    damage: {
      x: 1,
      dice: Dice.d6,
    },
    range: 10,
    isAbleToReceiveCharge: true,
    twoHanded: false,
    isSecondRank: true,
  },
  {
    id: 8,
    name: 'Staff', 
    cityCost: 5, 
    ruralCost: 3, 
    points: EncumbrancePoint.Regular, 
    isRecorded: true, 
    damage: {
      x: 1,
      dice: Dice.d4,
    },
    range: 5,
  },
  {
    id: 9,
    name: 'Weapon, Great',
    cityCost: 50,
    ruralCost: null,
    points: EncumbrancePoint.Oversized,
    isRecorded: true,
    damage: {
      x: 1,
      dice: Dice.d10,
    },
    range: 5,
    twoHanded: true,
  },
  {
    id: 10,
    name: 'Medium',
    cityCost: 20,
    ruralCost: 50, 
    points: EncumbrancePoint.Regular, 
    isRecorded: true, 
    damage: {
      x: 1,
      dice: Dice.d8,
    },
    range: 5,
    twoHanded: false,
  },
  {
    id: 11,
    name: 'Minor',
    cityCost: 5,
    ruralCost: 5, 
    points: EncumbrancePoint.Regular, 
    isRecorded: true, 
    damage: {
      x: 1,
      dice: Dice.d4,
    },
    range: 5,
  },
  {
    id: 12,
    name: 'Small',
    cityCost: 10,
    ruralCost: 10, 
    points: EncumbrancePoint.Regular, 
    isRecorded: true, 
    damage: {
      x: 1,
      dice: Dice.d6,
    },
    range: 5,
  },
  {
    id: 13,
    name: 'Whip',
    cityCost: 10,
    ruralCost: 25, 
    points: EncumbrancePoint.Regular, 
    isRecorded: true, 
    damage: {
      x: 1,
      dice: Dice.d3,
    },
    range: 10,
  },
]

// FIXME points