name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          # Set the BASE_PATH if your site is hosted at a subpath of your domain. For example, 'my-app' for 'username.github.io/my-app'
          # BASE_PATH: '/my-app'
          # If not, leave it empty
          BASE_PATH: ''
          NODE_ENV: 'production'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages  # The branch the action should deploy to.
          folder: out       # The folder the action should deploy.
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically creates this secret to use in your workflow.

      # Optional: Add a step to commit your Next.js build settings to your repository
      - name: Commit Next.js build files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f out
          git commit -m "Deploy Next.js build"
          git push
